## ################################
## Auth
## ################################

###
POST http://127.0.0.1:8080/api/v1/auth/registration
Content-Type: application/json

{
  "login": "login",
  "name": "sanya",
  "password": "000"
}

###
POST http://127.0.0.1:8080/api/v1/auth/login
Content-Type: application/json

{
  "login": "login",
  "password": "000"
}

> {% client.global.set("auth_token", response.body.token); %}

###
## ################################
## Profile
## ################################

###
GET http://127.0.0.1:8080/api/v1/profile/info
Content-Type: application/json
Authorization: Bearer {{auth_token}}

## ################################
## Project
## ################################

###
POST http://127.0.0.1:8080/api/v1/project
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "project 2",
  "description": "second test project for testing api"
}

###
PUT http://127.0.0.1:8080/api/v1/project/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "project 2 (update)",
  "description": "second test project for testing api"
}

###
GET http://127.0.0.1:8080/api/v1/project
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET http://127.0.0.1:8080/api/v1/project/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

## ################################
## Task
## ################################

###
POST http://127.0.0.1:8080/api/v1/task
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "projectId": 1,
  "title": "new task",
  "description": "description of task",
  "tags": [
    {
      "id": 1
    }
  ]
}

###
GET http://127.0.0.1:8080/api/v1/task/4
Content-Type: application/json
Authorization: Bearer {{auth_token}}

## ################################
## Tags
## ################################

###
POST http://127.0.0.1:8080/api/v1/tag
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "info",
  "color": 1
}

###
PUT http://127.0.0.1:8080/api/v1/tag/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "success",
  "color": 5
}

###
GET http://127.0.0.1:8080/api/v1/tag/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET http://127.0.0.1:8080/api/v1/tag/all
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET http://127.0.0.1:8080/api/v1/tag/colors
Content-Type: application/json
Authorization: Bearer {{auth_token}}
